name: model-wine-quality
on: [push]
jobs:
  run:
    run-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install requirements.txt
          python train.py

          echo "MODEL METRICS"
          cat metrics.txt
          